# -*- coding: utf-8 -*-
"""adivinhar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tCM_K9JfqshjNsEjtQ1GLWcRPcKhPHqE
"""

import os,random;
cont = 0
ac = 0
print("Bem-vindo!")
while True:
  print("Acerte o numero!")
  n1 = random.randrange(1,30)
  for i in range(5):
    print('quantidade de tentativas: {}'.format(5-i))
    palpite = int(input("Digite seu palpite: "))

    if palpite > n1 :
     print("Digite um numero Menor")
    if palpite < n1 :
     print("Digite um numero Maior")


    if n1 == palpite:
      ac +=1
      print("voce acertou!")
      break


  if n1 != palpite:
   print("voce nao acertou!")
   print('numero sorteado: {}'.format(n1))
  cont+= 1


  print('quantidade de jogadas: {}\nQuantidade de acertos: {}'.format(cont, ac))
  confirma = input("jogar de novo? [S/N]")
  print("|------------------------|")

  if confirma == 'n' or confirma == 'N':
        break