# -*- coding: utf-8 -*-
"""jokenpo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ovfgyvCivDoQJwg7DJbA29ucLbduQ8gn
"""

import os,random;

print("Bem-vindo!")

while True:
  print("Jo-Ken-Po")
  ac = 0
  emp = 0
  maq = 0
  cont = 0
  for i in range(10):
    print('quantidade de tentativas: {}'.format(10-i))
    n1 = random.randrange(1,3)
    print("[1] - Tesoura")
    print("[2] - Papel")
    print("[3] - Pedra")
    palpite = int(input('Escolha um dos apetrechos: '))
    if palpite > 3 or palpite < 1:
     print("digite um numero valido:")
     palpite = int(input('Escolha um dos apetrechos: '))

    if palpite == 1:
      print("Jogador : Tesoura")
    elif palpite == 2:
      print("Jogador : Papel")
    elif palpite == 3:
      print("Jogador : Pedra")

    if n1 == 1:
      print("Maquina : Tesoura")
    elif n1 == 2:
      print("Maquina : Papel")
    elif n1 == 3:
      print("Maquina : Pedra")


    if palpite == n1 :
     print("Empate!")
     emp += 1
    # tesoura e papel
    if palpite == 1 and n1 == 2:
     print("Jogador ganhou!")
     ac += 1
    # tesoura e pedra
    if palpite == 1 and n1 ==3:
     print("Maquina ganhou!")
     maq+=1

    # papel e tesoura
    if palpite == 2 and n1 == 1:
     print("Maquina ganhou!")
     maq+=1

    # papel e pedra
    if palpite == 2 and n1 ==3:
     print("Jogador ganhou!")
     ac +=1

    # pedra e tesoura
    if palpite == 3 and n1 == 1:
      print("Jogador ganhou!")
      ac +=1

    # pedra e papel
    if palpite == 3 and n1 == 2:
     print("Maquina ganhou!")
     maq+=1
    print("|-----Placar------|")

    print('Jogadas: {}\nJogador: {}\nMaquina: {}\nEmpates: {}'.format((i+1), ac, maq, emp))


  confirma = input("jogar de novo? [S/N]")
  print("|------------------------|")

  if confirma == 'n' or confirma == 'N':
        break

