# -*- coding: utf-8 -*-
"""Ope.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1izEWu5xsyOfPqC5qu26DfezFs662t57F
"""

import os,random;
cont = 0
ac = 0
while True:
  palpite = int(input("Digite seu palpite: "))
  n1 = random.randrange(1,10)
  n2 = random.randrange(1,10)
  op = random.randrange(1,4)
  num = 0
  if op == 1:
    num = n1 + n2
  if op == 2:
    num = n1 - n2
  if op == 3:
   ope = n1 * n2

  cont+= 1
  if num == palpite:
    ac +=1
    print("voce acertou!")
  else:
    print('voce nao acertou!')
    print('numero sorteado: {}'.format(num))
  print('quantidade de jogadas: {}\nQuantidade de acertos: {}'.format(cont, ac))
  confirma = input("jogar de novo? [S/N]")
  print("|------------------------|")

  if confirma == 'n' or confirma == 'N':
        break